apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfive-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: labfive
  template:
    metadata:
      labels:
        app: labfive
    spec:
      containers:
      - name: labfive-container
        # image: DOCKER_IMAGE_NAME:BUILD_NUMBER  # Using the BUILD_NUMBER as the image tag
        image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}  # Using the BUILD_NUMBER as the image tag

        ports:
        - containerPort: 8080