apiVersion: v1
kind: Service
metadata:
  name: labfive
spec:
  selector:
    app: your-app  # Повинно відповідати значенню matchLabels в Deployment
  ports:
    - protocol: TCP
      port: 80  # Порт, на який відкривається сервіс
      targetPort: 80  # Порт, на якому працює додаток в контейнері
  type: ClusterIP  # Тип сервісу (може бути NodePort, LoadBalancer і т. д.)
